# Generated by Django 5.0.6 on 2024-05-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('is_complected', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now=True)),
                ('upload_is', models.DateField(auto_now=True)),
            ],
        ),
    ]
